//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/DefaultInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DefaultInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DefaultInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""426f2270-adb0-41e6-8871-3fdec435cce3"",
            ""actions"": [
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""6a431d97-4d36-46ef-81bb-b158aa2b5841"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Tactical Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""b58adad5-de06-40f9-9425-a0a21626b52e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""710dd8b9-77b2-4471-a5a1-a99bae97010d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""4f09e4b0-4ed9-48ae-92d8-529739b4eaba"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""f961a794-581d-4673-bde8-01af12f4f3e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""678e9d56-88df-4e1b-a477-983a88c9bd60"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heal"",
                    ""type"": ""Button"",
                    ""id"": ""29670c12-d427-4cb1-ab26-ff1d26e3d6f6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Value"",
                    ""id"": ""6a2f436f-2f32-4cec-b84e-d4bf83bbd37e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Slide"",
                    ""type"": ""Button"",
                    ""id"": ""8280eb36-0a9c-4918-8571-e231145f22da"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""225b7ad6-9fec-48e8-8658-00e5f7863829"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraControl"",
                    ""type"": ""Value"",
                    ""id"": ""888c05dd-806b-45f7-9300-2a71a8c7277e"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NormalizedPlayerCameraControl"",
                    ""type"": ""Value"",
                    ""id"": ""db5bb732-b5a2-49c9-84c0-f51c38edb25c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThrowEquipment"",
                    ""type"": ""Button"",
                    ""id"": ""362b5de3-8203-44f1-af3e-357ce59ec32a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MainWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""4ba01783-b868-4ed5-be78-b99d061a6c80"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""1aed2041-0e4c-4552-a3bf-3516eaf14c44"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""ccd99a1f-61b8-4ac7-b297-dcd884ecb2e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponCycle"",
                    ""type"": ""Button"",
                    ""id"": ""d19e3fd8-60c7-40d3-b3af-42f3fcc90816"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""7f21431a-30f4-4a45-9551-e0cb259eb8eb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickUp"",
                    ""type"": ""Button"",
                    ""id"": ""16f2472e-dbf8-430c-8344-90e5c8efa42e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hit"",
                    ""type"": ""Button"",
                    ""id"": ""c85be194-0857-489b-8f81-6b7e7d666f25"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bash"",
                    ""type"": ""Button"",
                    ""id"": ""4ae2f1ee-f5d2-40af-8c22-6b241ad8bd04"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""959147d4-962f-401b-b5d0-b3ba2a36b201"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c7b2ec08-bade-4f40-9fa5-54e4c153a259"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e031bef9-eaaa-4b57-b11f-a681c5a88e15"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Tactical Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1ac73a1-746b-4af2-97af-c024a7a3eb4c"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Tactical Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b0f3869-d70c-47eb-8bd3-e38fe3af149d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae42021f-7386-4ee5-aac8-a595de5adbd2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81eddcbb-9208-49e9-9317-fe3c746cec16"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2dbc83e0-2c7d-4eef-9534-e018ad322afc"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ace66d42-34a4-4c69-8f75-d83803bc1e42"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e682abb8-34e0-4db1-9272-452f8a800a80"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""554dc0a6-8b58-4b4c-917a-8aac1da20729"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""992fd893-679f-4354-9b7c-4eb4c152c7cb"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d75a7718-f463-455a-bd54-5da413830a8c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""39eb1a56-0c7b-4491-b8ca-3cd45b3acf0c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""aa84afb1-0848-498f-9ef8-b148a2e136a6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b778ddb5-7397-461b-81e4-9fb22e6fb09f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8abb5f58-27b5-4248-8c5c-f87466d35e6a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""076e4908-7c29-4b6f-8e37-20bd147890da"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8a556944-e8be-4a11-825b-1d2ac3fe830c"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""NormalizedPlayerCameraControl"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""341a81f0-f0e2-4a45-9270-a29fc8afaf36"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalizedPlayerCameraControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c582721c-4b14-4c6d-892b-9a92ebc25120"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalizedPlayerCameraControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""889eb7f9-8b08-4ee6-ab33-5e84551c1490"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalizedPlayerCameraControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3e67dc67-f4f0-485d-ba73-32bfc52ecfeb"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalizedPlayerCameraControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f3564b76-8c89-48e7-8ece-40f7c0ecc5c8"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowEquipment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""527b59cc-14ae-450d-a196-7424412aab1d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a67d7712-dc71-47f4-8313-617fd084c530"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68bec547-e801-4714-81e5-4493fd36d38d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5ebf9804-6fd7-41a9-a628-52d0ca3c1f49"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponCycle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1608a050-1d96-444e-b8e6-e619103f77b8"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponCycle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e3ca5a95-2428-48dc-b062-e54bbbc2c773"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponCycle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1d7aca94-a56b-4180-a674-ba27182185e8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a2b8aeb-61db-4382-bfdb-5e7c857fa34f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""448d2738-3550-4ccf-8ca3-506e80bee45d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37cb1e23-2d4f-4b71-96bf-a897e33502fa"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b999857-119b-4f04-aeb1-3b8b3538073b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold,Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TextChat"",
            ""id"": ""f94bf612-e4f7-40f5-99e1-361c9ce48bb1"",
            ""actions"": [
                {
                    ""name"": ""SwitchChat"",
                    ""type"": ""Button"",
                    ""id"": ""9e7861c7-d376-4918-98b7-dc2e99615613"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenChat"",
                    ""type"": ""Button"",
                    ""id"": ""f6ec66e5-4be3-488b-9ad6-1f5775d8d965"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseChat"",
                    ""type"": ""Button"",
                    ""id"": ""5ab61e2a-f496-4cdf-89be-926669545893"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0fd8d1cf-3d71-4923-9f4c-3eff593fd83e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchChat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c022150-7048-477d-989f-c6e3cf10939c"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenChat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d870e1e-be65-474d-adb6-57640139f0e3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseChat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Scoreboard"",
            ""id"": ""e230078a-6e75-4a69-a29d-b3fceefa3694"",
            ""actions"": [
                {
                    ""name"": ""OpenCloseScoreboard"",
                    ""type"": ""Button"",
                    ""id"": ""cc603be3-c9a2-41f7-adf0-98e1b08de276"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2),Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""48b36b8c-7a0b-4baf-a9e2-5574ae30c0c7"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCloseScoreboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PauseMenu"",
            ""id"": ""7bff02c5-29d3-42be-9013-fa41a40cf135"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""7676bf88-c9dd-41d7-88a9-b009eb7109a6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""319e9e42-2d1a-427e-a087-57693bf68102"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RespawnMenu"",
            ""id"": ""61c56fe4-675a-433f-8479-75fc5ac2be96"",
            ""actions"": [
                {
                    ""name"": ""Respawn"",
                    ""type"": ""Button"",
                    ""id"": ""89fdb029-ce6f-4fef-8f45-cd65e9e4677b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwipeLeft"",
                    ""type"": ""Button"",
                    ""id"": ""b14db678-8582-4cb4-9f1d-9672f48308b6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwipeRight"",
                    ""type"": ""Button"",
                    ""id"": ""84e89c74-0cb7-4a0a-91d5-3dc37aea8cc4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""47cdfd03-5c11-4e2a-bb3a-49910a37f32a"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecd774cb-93ea-41da-8f05-6755e8bf7c05"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""158d8581-e584-4291-b4d8-382d772cba9d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""VoiceChat"",
            ""id"": ""fbfd26b5-b601-4807-b710-2f17860a7aa5"",
            ""actions"": [
                {
                    ""name"": ""Speak"",
                    ""type"": ""Button"",
                    ""id"": ""f982e4eb-2fc9-4f44-ac1e-f550aeb73e16"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""02d6901b-df4b-4e35-9c48-08adae439195"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speak"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu"",
            ""id"": ""97834e47-e1ca-432f-bd3f-5228bfa3b8db"",
            ""actions"": [
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""b71c5d1e-35f3-458b-a626-e498e93f4d2a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ac808675-40fb-45c1-8940-6c19fc487fbd"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FreeCamera"",
            ""id"": ""33632846-6058-4870-8304-86766b42164b"",
            ""actions"": [
                {
                    ""name"": ""CameraControl"",
                    ""type"": ""Value"",
                    ""id"": ""ddb2332d-bb53-4601-8318-33d2caca9efe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d6c36f4d-d5da-420f-bde2-1bb99df7df70"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""e4d9ef9e-dceb-44ee-a261-2ea827d8d3fd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIToggle"",
                    ""type"": ""Button"",
                    ""id"": ""23c757a0-c182-4322-ad3a-6dcca75992ec"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""21f7a26e-19d9-4a53-bca8-62df7b1d9b49"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""VerticalMove"",
                    ""type"": ""Value"",
                    ""id"": ""c1d312aa-970c-49df-98ba-2dcd821f0b5b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""05252bbf-7229-4612-852d-714b0b5f0afe"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bfa0265e-9978-44af-ad8c-4ddd9402b629"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1eef1461-5d63-43a3-8549-b550cce143c2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b1ad2736-37be-4ef3-8b18-feffb7b6c458"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""43582e08-37a0-4aa9-805d-b48deb1e7937"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""956d0f4f-76b0-41b5-abdd-1a18e501b54a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b89273a0-d532-4b66-8c43-db44aebad47c"",
                    ""path"": ""<Keyboard>/f12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3911dd95-330e-4ce8-95d4-00607335edbd"",
                    ""path"": ""<Keyboard>/f11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""574a7496-fdc1-4087-bf6e-914ef1e3f412"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""46ceac8f-4d7f-47c6-87ae-5cbaa6b740cc"",
                    ""path"": ""1DAxis(whichSideWins=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""54858492-f334-441c-8396-3d4383354e01"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""bab392bf-f387-4337-8610-da3acc33a584"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Shoot = m_Player.FindAction("Shoot", throwIfNotFound: true);
        m_Player_TacticalSprint = m_Player.FindAction("Tactical Sprint", throwIfNotFound: true);
        m_Player_Reload = m_Player.FindAction("Reload", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_Heal = m_Player.FindAction("Heal", throwIfNotFound: true);
        m_Player_Aim = m_Player.FindAction("Aim", throwIfNotFound: true);
        m_Player_Slide = m_Player.FindAction("Slide", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_CameraControl = m_Player.FindAction("CameraControl", throwIfNotFound: true);
        m_Player_NormalizedPlayerCameraControl = m_Player.FindAction("NormalizedPlayerCameraControl", throwIfNotFound: true);
        m_Player_ThrowEquipment = m_Player.FindAction("ThrowEquipment", throwIfNotFound: true);
        m_Player_MainWeapon = m_Player.FindAction("MainWeapon", throwIfNotFound: true);
        m_Player_SecondaryWeapon = m_Player.FindAction("SecondaryWeapon", throwIfNotFound: true);
        m_Player_ThirdWeapon = m_Player.FindAction("ThirdWeapon", throwIfNotFound: true);
        m_Player_WeaponCycle = m_Player.FindAction("WeaponCycle", throwIfNotFound: true);
        m_Player_Throw = m_Player.FindAction("Throw", throwIfNotFound: true);
        m_Player_PickUp = m_Player.FindAction("PickUp", throwIfNotFound: true);
        m_Player_Hit = m_Player.FindAction("Hit", throwIfNotFound: true);
        m_Player_Bash = m_Player.FindAction("Bash", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        // TextChat
        m_TextChat = asset.FindActionMap("TextChat", throwIfNotFound: true);
        m_TextChat_SwitchChat = m_TextChat.FindAction("SwitchChat", throwIfNotFound: true);
        m_TextChat_OpenChat = m_TextChat.FindAction("OpenChat", throwIfNotFound: true);
        m_TextChat_CloseChat = m_TextChat.FindAction("CloseChat", throwIfNotFound: true);
        // Scoreboard
        m_Scoreboard = asset.FindActionMap("Scoreboard", throwIfNotFound: true);
        m_Scoreboard_OpenCloseScoreboard = m_Scoreboard.FindAction("OpenCloseScoreboard", throwIfNotFound: true);
        // PauseMenu
        m_PauseMenu = asset.FindActionMap("PauseMenu", throwIfNotFound: true);
        m_PauseMenu_Pause = m_PauseMenu.FindAction("Pause", throwIfNotFound: true);
        // RespawnMenu
        m_RespawnMenu = asset.FindActionMap("RespawnMenu", throwIfNotFound: true);
        m_RespawnMenu_Respawn = m_RespawnMenu.FindAction("Respawn", throwIfNotFound: true);
        m_RespawnMenu_SwipeLeft = m_RespawnMenu.FindAction("SwipeLeft", throwIfNotFound: true);
        m_RespawnMenu_SwipeRight = m_RespawnMenu.FindAction("SwipeRight", throwIfNotFound: true);
        // VoiceChat
        m_VoiceChat = asset.FindActionMap("VoiceChat", throwIfNotFound: true);
        m_VoiceChat_Speak = m_VoiceChat.FindAction("Speak", throwIfNotFound: true);
        // MainMenu
        m_MainMenu = asset.FindActionMap("MainMenu", throwIfNotFound: true);
        m_MainMenu_Escape = m_MainMenu.FindAction("Escape", throwIfNotFound: true);
        // FreeCamera
        m_FreeCamera = asset.FindActionMap("FreeCamera", throwIfNotFound: true);
        m_FreeCamera_CameraControl = m_FreeCamera.FindAction("CameraControl", throwIfNotFound: true);
        m_FreeCamera_Move = m_FreeCamera.FindAction("Move", throwIfNotFound: true);
        m_FreeCamera_Toggle = m_FreeCamera.FindAction("Toggle", throwIfNotFound: true);
        m_FreeCamera_UIToggle = m_FreeCamera.FindAction("UIToggle", throwIfNotFound: true);
        m_FreeCamera_Scroll = m_FreeCamera.FindAction("Scroll", throwIfNotFound: true);
        m_FreeCamera_VerticalMove = m_FreeCamera.FindAction("VerticalMove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Shoot;
    private readonly InputAction m_Player_TacticalSprint;
    private readonly InputAction m_Player_Reload;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_Heal;
    private readonly InputAction m_Player_Aim;
    private readonly InputAction m_Player_Slide;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_CameraControl;
    private readonly InputAction m_Player_NormalizedPlayerCameraControl;
    private readonly InputAction m_Player_ThrowEquipment;
    private readonly InputAction m_Player_MainWeapon;
    private readonly InputAction m_Player_SecondaryWeapon;
    private readonly InputAction m_Player_ThirdWeapon;
    private readonly InputAction m_Player_WeaponCycle;
    private readonly InputAction m_Player_Throw;
    private readonly InputAction m_Player_PickUp;
    private readonly InputAction m_Player_Hit;
    private readonly InputAction m_Player_Bash;
    private readonly InputAction m_Player_Interact;
    public struct PlayerActions
    {
        private @DefaultInput m_Wrapper;
        public PlayerActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shoot => m_Wrapper.m_Player_Shoot;
        public InputAction @TacticalSprint => m_Wrapper.m_Player_TacticalSprint;
        public InputAction @Reload => m_Wrapper.m_Player_Reload;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @Heal => m_Wrapper.m_Player_Heal;
        public InputAction @Aim => m_Wrapper.m_Player_Aim;
        public InputAction @Slide => m_Wrapper.m_Player_Slide;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @CameraControl => m_Wrapper.m_Player_CameraControl;
        public InputAction @NormalizedPlayerCameraControl => m_Wrapper.m_Player_NormalizedPlayerCameraControl;
        public InputAction @ThrowEquipment => m_Wrapper.m_Player_ThrowEquipment;
        public InputAction @MainWeapon => m_Wrapper.m_Player_MainWeapon;
        public InputAction @SecondaryWeapon => m_Wrapper.m_Player_SecondaryWeapon;
        public InputAction @ThirdWeapon => m_Wrapper.m_Player_ThirdWeapon;
        public InputAction @WeaponCycle => m_Wrapper.m_Player_WeaponCycle;
        public InputAction @Throw => m_Wrapper.m_Player_Throw;
        public InputAction @PickUp => m_Wrapper.m_Player_PickUp;
        public InputAction @Hit => m_Wrapper.m_Player_Hit;
        public InputAction @Bash => m_Wrapper.m_Player_Bash;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @TacticalSprint.started += instance.OnTacticalSprint;
            @TacticalSprint.performed += instance.OnTacticalSprint;
            @TacticalSprint.canceled += instance.OnTacticalSprint;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Heal.started += instance.OnHeal;
            @Heal.performed += instance.OnHeal;
            @Heal.canceled += instance.OnHeal;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @Slide.started += instance.OnSlide;
            @Slide.performed += instance.OnSlide;
            @Slide.canceled += instance.OnSlide;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @CameraControl.started += instance.OnCameraControl;
            @CameraControl.performed += instance.OnCameraControl;
            @CameraControl.canceled += instance.OnCameraControl;
            @NormalizedPlayerCameraControl.started += instance.OnNormalizedPlayerCameraControl;
            @NormalizedPlayerCameraControl.performed += instance.OnNormalizedPlayerCameraControl;
            @NormalizedPlayerCameraControl.canceled += instance.OnNormalizedPlayerCameraControl;
            @ThrowEquipment.started += instance.OnThrowEquipment;
            @ThrowEquipment.performed += instance.OnThrowEquipment;
            @ThrowEquipment.canceled += instance.OnThrowEquipment;
            @MainWeapon.started += instance.OnMainWeapon;
            @MainWeapon.performed += instance.OnMainWeapon;
            @MainWeapon.canceled += instance.OnMainWeapon;
            @SecondaryWeapon.started += instance.OnSecondaryWeapon;
            @SecondaryWeapon.performed += instance.OnSecondaryWeapon;
            @SecondaryWeapon.canceled += instance.OnSecondaryWeapon;
            @ThirdWeapon.started += instance.OnThirdWeapon;
            @ThirdWeapon.performed += instance.OnThirdWeapon;
            @ThirdWeapon.canceled += instance.OnThirdWeapon;
            @WeaponCycle.started += instance.OnWeaponCycle;
            @WeaponCycle.performed += instance.OnWeaponCycle;
            @WeaponCycle.canceled += instance.OnWeaponCycle;
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @PickUp.started += instance.OnPickUp;
            @PickUp.performed += instance.OnPickUp;
            @PickUp.canceled += instance.OnPickUp;
            @Hit.started += instance.OnHit;
            @Hit.performed += instance.OnHit;
            @Hit.canceled += instance.OnHit;
            @Bash.started += instance.OnBash;
            @Bash.performed += instance.OnBash;
            @Bash.canceled += instance.OnBash;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @TacticalSprint.started -= instance.OnTacticalSprint;
            @TacticalSprint.performed -= instance.OnTacticalSprint;
            @TacticalSprint.canceled -= instance.OnTacticalSprint;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Heal.started -= instance.OnHeal;
            @Heal.performed -= instance.OnHeal;
            @Heal.canceled -= instance.OnHeal;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @Slide.started -= instance.OnSlide;
            @Slide.performed -= instance.OnSlide;
            @Slide.canceled -= instance.OnSlide;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @CameraControl.started -= instance.OnCameraControl;
            @CameraControl.performed -= instance.OnCameraControl;
            @CameraControl.canceled -= instance.OnCameraControl;
            @NormalizedPlayerCameraControl.started -= instance.OnNormalizedPlayerCameraControl;
            @NormalizedPlayerCameraControl.performed -= instance.OnNormalizedPlayerCameraControl;
            @NormalizedPlayerCameraControl.canceled -= instance.OnNormalizedPlayerCameraControl;
            @ThrowEquipment.started -= instance.OnThrowEquipment;
            @ThrowEquipment.performed -= instance.OnThrowEquipment;
            @ThrowEquipment.canceled -= instance.OnThrowEquipment;
            @MainWeapon.started -= instance.OnMainWeapon;
            @MainWeapon.performed -= instance.OnMainWeapon;
            @MainWeapon.canceled -= instance.OnMainWeapon;
            @SecondaryWeapon.started -= instance.OnSecondaryWeapon;
            @SecondaryWeapon.performed -= instance.OnSecondaryWeapon;
            @SecondaryWeapon.canceled -= instance.OnSecondaryWeapon;
            @ThirdWeapon.started -= instance.OnThirdWeapon;
            @ThirdWeapon.performed -= instance.OnThirdWeapon;
            @ThirdWeapon.canceled -= instance.OnThirdWeapon;
            @WeaponCycle.started -= instance.OnWeaponCycle;
            @WeaponCycle.performed -= instance.OnWeaponCycle;
            @WeaponCycle.canceled -= instance.OnWeaponCycle;
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @PickUp.started -= instance.OnPickUp;
            @PickUp.performed -= instance.OnPickUp;
            @PickUp.canceled -= instance.OnPickUp;
            @Hit.started -= instance.OnHit;
            @Hit.performed -= instance.OnHit;
            @Hit.canceled -= instance.OnHit;
            @Bash.started -= instance.OnBash;
            @Bash.performed -= instance.OnBash;
            @Bash.canceled -= instance.OnBash;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // TextChat
    private readonly InputActionMap m_TextChat;
    private List<ITextChatActions> m_TextChatActionsCallbackInterfaces = new List<ITextChatActions>();
    private readonly InputAction m_TextChat_SwitchChat;
    private readonly InputAction m_TextChat_OpenChat;
    private readonly InputAction m_TextChat_CloseChat;
    public struct TextChatActions
    {
        private @DefaultInput m_Wrapper;
        public TextChatActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchChat => m_Wrapper.m_TextChat_SwitchChat;
        public InputAction @OpenChat => m_Wrapper.m_TextChat_OpenChat;
        public InputAction @CloseChat => m_Wrapper.m_TextChat_CloseChat;
        public InputActionMap Get() { return m_Wrapper.m_TextChat; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TextChatActions set) { return set.Get(); }
        public void AddCallbacks(ITextChatActions instance)
        {
            if (instance == null || m_Wrapper.m_TextChatActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TextChatActionsCallbackInterfaces.Add(instance);
            @SwitchChat.started += instance.OnSwitchChat;
            @SwitchChat.performed += instance.OnSwitchChat;
            @SwitchChat.canceled += instance.OnSwitchChat;
            @OpenChat.started += instance.OnOpenChat;
            @OpenChat.performed += instance.OnOpenChat;
            @OpenChat.canceled += instance.OnOpenChat;
            @CloseChat.started += instance.OnCloseChat;
            @CloseChat.performed += instance.OnCloseChat;
            @CloseChat.canceled += instance.OnCloseChat;
        }

        private void UnregisterCallbacks(ITextChatActions instance)
        {
            @SwitchChat.started -= instance.OnSwitchChat;
            @SwitchChat.performed -= instance.OnSwitchChat;
            @SwitchChat.canceled -= instance.OnSwitchChat;
            @OpenChat.started -= instance.OnOpenChat;
            @OpenChat.performed -= instance.OnOpenChat;
            @OpenChat.canceled -= instance.OnOpenChat;
            @CloseChat.started -= instance.OnCloseChat;
            @CloseChat.performed -= instance.OnCloseChat;
            @CloseChat.canceled -= instance.OnCloseChat;
        }

        public void RemoveCallbacks(ITextChatActions instance)
        {
            if (m_Wrapper.m_TextChatActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITextChatActions instance)
        {
            foreach (var item in m_Wrapper.m_TextChatActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TextChatActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TextChatActions @TextChat => new TextChatActions(this);

    // Scoreboard
    private readonly InputActionMap m_Scoreboard;
    private List<IScoreboardActions> m_ScoreboardActionsCallbackInterfaces = new List<IScoreboardActions>();
    private readonly InputAction m_Scoreboard_OpenCloseScoreboard;
    public struct ScoreboardActions
    {
        private @DefaultInput m_Wrapper;
        public ScoreboardActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenCloseScoreboard => m_Wrapper.m_Scoreboard_OpenCloseScoreboard;
        public InputActionMap Get() { return m_Wrapper.m_Scoreboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ScoreboardActions set) { return set.Get(); }
        public void AddCallbacks(IScoreboardActions instance)
        {
            if (instance == null || m_Wrapper.m_ScoreboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ScoreboardActionsCallbackInterfaces.Add(instance);
            @OpenCloseScoreboard.started += instance.OnOpenCloseScoreboard;
            @OpenCloseScoreboard.performed += instance.OnOpenCloseScoreboard;
            @OpenCloseScoreboard.canceled += instance.OnOpenCloseScoreboard;
        }

        private void UnregisterCallbacks(IScoreboardActions instance)
        {
            @OpenCloseScoreboard.started -= instance.OnOpenCloseScoreboard;
            @OpenCloseScoreboard.performed -= instance.OnOpenCloseScoreboard;
            @OpenCloseScoreboard.canceled -= instance.OnOpenCloseScoreboard;
        }

        public void RemoveCallbacks(IScoreboardActions instance)
        {
            if (m_Wrapper.m_ScoreboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IScoreboardActions instance)
        {
            foreach (var item in m_Wrapper.m_ScoreboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ScoreboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ScoreboardActions @Scoreboard => new ScoreboardActions(this);

    // PauseMenu
    private readonly InputActionMap m_PauseMenu;
    private List<IPauseMenuActions> m_PauseMenuActionsCallbackInterfaces = new List<IPauseMenuActions>();
    private readonly InputAction m_PauseMenu_Pause;
    public struct PauseMenuActions
    {
        private @DefaultInput m_Wrapper;
        public PauseMenuActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_PauseMenu_Pause;
        public InputActionMap Get() { return m_Wrapper.m_PauseMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseMenuActions set) { return set.Get(); }
        public void AddCallbacks(IPauseMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_PauseMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PauseMenuActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IPauseMenuActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IPauseMenuActions instance)
        {
            if (m_Wrapper.m_PauseMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPauseMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_PauseMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PauseMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PauseMenuActions @PauseMenu => new PauseMenuActions(this);

    // RespawnMenu
    private readonly InputActionMap m_RespawnMenu;
    private List<IRespawnMenuActions> m_RespawnMenuActionsCallbackInterfaces = new List<IRespawnMenuActions>();
    private readonly InputAction m_RespawnMenu_Respawn;
    private readonly InputAction m_RespawnMenu_SwipeLeft;
    private readonly InputAction m_RespawnMenu_SwipeRight;
    public struct RespawnMenuActions
    {
        private @DefaultInput m_Wrapper;
        public RespawnMenuActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Respawn => m_Wrapper.m_RespawnMenu_Respawn;
        public InputAction @SwipeLeft => m_Wrapper.m_RespawnMenu_SwipeLeft;
        public InputAction @SwipeRight => m_Wrapper.m_RespawnMenu_SwipeRight;
        public InputActionMap Get() { return m_Wrapper.m_RespawnMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RespawnMenuActions set) { return set.Get(); }
        public void AddCallbacks(IRespawnMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_RespawnMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RespawnMenuActionsCallbackInterfaces.Add(instance);
            @Respawn.started += instance.OnRespawn;
            @Respawn.performed += instance.OnRespawn;
            @Respawn.canceled += instance.OnRespawn;
            @SwipeLeft.started += instance.OnSwipeLeft;
            @SwipeLeft.performed += instance.OnSwipeLeft;
            @SwipeLeft.canceled += instance.OnSwipeLeft;
            @SwipeRight.started += instance.OnSwipeRight;
            @SwipeRight.performed += instance.OnSwipeRight;
            @SwipeRight.canceled += instance.OnSwipeRight;
        }

        private void UnregisterCallbacks(IRespawnMenuActions instance)
        {
            @Respawn.started -= instance.OnRespawn;
            @Respawn.performed -= instance.OnRespawn;
            @Respawn.canceled -= instance.OnRespawn;
            @SwipeLeft.started -= instance.OnSwipeLeft;
            @SwipeLeft.performed -= instance.OnSwipeLeft;
            @SwipeLeft.canceled -= instance.OnSwipeLeft;
            @SwipeRight.started -= instance.OnSwipeRight;
            @SwipeRight.performed -= instance.OnSwipeRight;
            @SwipeRight.canceled -= instance.OnSwipeRight;
        }

        public void RemoveCallbacks(IRespawnMenuActions instance)
        {
            if (m_Wrapper.m_RespawnMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRespawnMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_RespawnMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RespawnMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RespawnMenuActions @RespawnMenu => new RespawnMenuActions(this);

    // VoiceChat
    private readonly InputActionMap m_VoiceChat;
    private List<IVoiceChatActions> m_VoiceChatActionsCallbackInterfaces = new List<IVoiceChatActions>();
    private readonly InputAction m_VoiceChat_Speak;
    public struct VoiceChatActions
    {
        private @DefaultInput m_Wrapper;
        public VoiceChatActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Speak => m_Wrapper.m_VoiceChat_Speak;
        public InputActionMap Get() { return m_Wrapper.m_VoiceChat; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VoiceChatActions set) { return set.Get(); }
        public void AddCallbacks(IVoiceChatActions instance)
        {
            if (instance == null || m_Wrapper.m_VoiceChatActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VoiceChatActionsCallbackInterfaces.Add(instance);
            @Speak.started += instance.OnSpeak;
            @Speak.performed += instance.OnSpeak;
            @Speak.canceled += instance.OnSpeak;
        }

        private void UnregisterCallbacks(IVoiceChatActions instance)
        {
            @Speak.started -= instance.OnSpeak;
            @Speak.performed -= instance.OnSpeak;
            @Speak.canceled -= instance.OnSpeak;
        }

        public void RemoveCallbacks(IVoiceChatActions instance)
        {
            if (m_Wrapper.m_VoiceChatActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVoiceChatActions instance)
        {
            foreach (var item in m_Wrapper.m_VoiceChatActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VoiceChatActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VoiceChatActions @VoiceChat => new VoiceChatActions(this);

    // MainMenu
    private readonly InputActionMap m_MainMenu;
    private List<IMainMenuActions> m_MainMenuActionsCallbackInterfaces = new List<IMainMenuActions>();
    private readonly InputAction m_MainMenu_Escape;
    public struct MainMenuActions
    {
        private @DefaultInput m_Wrapper;
        public MainMenuActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Escape => m_Wrapper.m_MainMenu_Escape;
        public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
        public void AddCallbacks(IMainMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MainMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainMenuActionsCallbackInterfaces.Add(instance);
            @Escape.started += instance.OnEscape;
            @Escape.performed += instance.OnEscape;
            @Escape.canceled += instance.OnEscape;
        }

        private void UnregisterCallbacks(IMainMenuActions instance)
        {
            @Escape.started -= instance.OnEscape;
            @Escape.performed -= instance.OnEscape;
            @Escape.canceled -= instance.OnEscape;
        }

        public void RemoveCallbacks(IMainMenuActions instance)
        {
            if (m_Wrapper.m_MainMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MainMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainMenuActions @MainMenu => new MainMenuActions(this);

    // FreeCamera
    private readonly InputActionMap m_FreeCamera;
    private List<IFreeCameraActions> m_FreeCameraActionsCallbackInterfaces = new List<IFreeCameraActions>();
    private readonly InputAction m_FreeCamera_CameraControl;
    private readonly InputAction m_FreeCamera_Move;
    private readonly InputAction m_FreeCamera_Toggle;
    private readonly InputAction m_FreeCamera_UIToggle;
    private readonly InputAction m_FreeCamera_Scroll;
    private readonly InputAction m_FreeCamera_VerticalMove;
    public struct FreeCameraActions
    {
        private @DefaultInput m_Wrapper;
        public FreeCameraActions(@DefaultInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CameraControl => m_Wrapper.m_FreeCamera_CameraControl;
        public InputAction @Move => m_Wrapper.m_FreeCamera_Move;
        public InputAction @Toggle => m_Wrapper.m_FreeCamera_Toggle;
        public InputAction @UIToggle => m_Wrapper.m_FreeCamera_UIToggle;
        public InputAction @Scroll => m_Wrapper.m_FreeCamera_Scroll;
        public InputAction @VerticalMove => m_Wrapper.m_FreeCamera_VerticalMove;
        public InputActionMap Get() { return m_Wrapper.m_FreeCamera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FreeCameraActions set) { return set.Get(); }
        public void AddCallbacks(IFreeCameraActions instance)
        {
            if (instance == null || m_Wrapper.m_FreeCameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FreeCameraActionsCallbackInterfaces.Add(instance);
            @CameraControl.started += instance.OnCameraControl;
            @CameraControl.performed += instance.OnCameraControl;
            @CameraControl.canceled += instance.OnCameraControl;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Toggle.started += instance.OnToggle;
            @Toggle.performed += instance.OnToggle;
            @Toggle.canceled += instance.OnToggle;
            @UIToggle.started += instance.OnUIToggle;
            @UIToggle.performed += instance.OnUIToggle;
            @UIToggle.canceled += instance.OnUIToggle;
            @Scroll.started += instance.OnScroll;
            @Scroll.performed += instance.OnScroll;
            @Scroll.canceled += instance.OnScroll;
            @VerticalMove.started += instance.OnVerticalMove;
            @VerticalMove.performed += instance.OnVerticalMove;
            @VerticalMove.canceled += instance.OnVerticalMove;
        }

        private void UnregisterCallbacks(IFreeCameraActions instance)
        {
            @CameraControl.started -= instance.OnCameraControl;
            @CameraControl.performed -= instance.OnCameraControl;
            @CameraControl.canceled -= instance.OnCameraControl;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Toggle.started -= instance.OnToggle;
            @Toggle.performed -= instance.OnToggle;
            @Toggle.canceled -= instance.OnToggle;
            @UIToggle.started -= instance.OnUIToggle;
            @UIToggle.performed -= instance.OnUIToggle;
            @UIToggle.canceled -= instance.OnUIToggle;
            @Scroll.started -= instance.OnScroll;
            @Scroll.performed -= instance.OnScroll;
            @Scroll.canceled -= instance.OnScroll;
            @VerticalMove.started -= instance.OnVerticalMove;
            @VerticalMove.performed -= instance.OnVerticalMove;
            @VerticalMove.canceled -= instance.OnVerticalMove;
        }

        public void RemoveCallbacks(IFreeCameraActions instance)
        {
            if (m_Wrapper.m_FreeCameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFreeCameraActions instance)
        {
            foreach (var item in m_Wrapper.m_FreeCameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FreeCameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FreeCameraActions @FreeCamera => new FreeCameraActions(this);
    public interface IPlayerActions
    {
        void OnShoot(InputAction.CallbackContext context);
        void OnTacticalSprint(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnHeal(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnSlide(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnCameraControl(InputAction.CallbackContext context);
        void OnNormalizedPlayerCameraControl(InputAction.CallbackContext context);
        void OnThrowEquipment(InputAction.CallbackContext context);
        void OnMainWeapon(InputAction.CallbackContext context);
        void OnSecondaryWeapon(InputAction.CallbackContext context);
        void OnThirdWeapon(InputAction.CallbackContext context);
        void OnWeaponCycle(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnPickUp(InputAction.CallbackContext context);
        void OnHit(InputAction.CallbackContext context);
        void OnBash(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface ITextChatActions
    {
        void OnSwitchChat(InputAction.CallbackContext context);
        void OnOpenChat(InputAction.CallbackContext context);
        void OnCloseChat(InputAction.CallbackContext context);
    }
    public interface IScoreboardActions
    {
        void OnOpenCloseScoreboard(InputAction.CallbackContext context);
    }
    public interface IPauseMenuActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
    public interface IRespawnMenuActions
    {
        void OnRespawn(InputAction.CallbackContext context);
        void OnSwipeLeft(InputAction.CallbackContext context);
        void OnSwipeRight(InputAction.CallbackContext context);
    }
    public interface IVoiceChatActions
    {
        void OnSpeak(InputAction.CallbackContext context);
    }
    public interface IMainMenuActions
    {
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IFreeCameraActions
    {
        void OnCameraControl(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnToggle(InputAction.CallbackContext context);
        void OnUIToggle(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnVerticalMove(InputAction.CallbackContext context);
    }
}
